#!/usr/bin/env bash
# This script installs nginx on a server that listens on port 80
# returns a page with the string Hello world

apt-get -y update
apt-get -y install nginx
echo "Hello world!" | tee /var/www/html/index.html
service nginx restart
