#!/usr/bin/env bash
# This script configures a nginx server so that
# redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ parmanent;' /etc/nginx/sites-available/default

service nginx restart
