#!/usr/bin/env bash
# This script installs and configures HAproxy on a server
sudo apt-get -y update

# enable a dedicated ppa
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy=2.0.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.original}

cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg

frontend haproxy_balancer
	bind *:80
	mode http
	default_backend myservers

backend myservers
	balance roundrobin
	server 327055-web-01 100.26.209.142 check
	server 327055-web-02 54.158.214.70 check
EOF

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
