#!/usr/bin/env bash
# This script installs and configures HAproxy on a server
sudo apt-get -y update

sudo apt-get -y install haproxy=2.0.\*

sudo service haproxy start
sudo cp -a /etc/haproxy/haproxy.cfg{,.original}

echo '
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend myservers

backend myservers
	balance roundrobin
	server 327055-web-01 100.26.209.142:80 check
	server 327055-web-02 54.158.214.70:80 check' >>
sudo /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
