#!/usr/bin/env bash
# This script makes sure nginx is listening at port 80

sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server;/' /etc/sites-enabled/default
sudo service nginx restart
