#!/usr/bin/env bash
# This script makes a story based on the content of passwd file

file="/etc/passwd"
while IFS=: read -r username passwd uid gid full_name home_dir shell
do
	echo "The $username is part of the $gid gang, lives in $home_dir and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $full_name"
done < "$file"
