#!/usr/bin/env bash
# Displays numbers from 1-20 and 
# on the 4th loop it also displays "bad luck from china"
# on the 9th loop dispalys"bad luck from japan"
# on the 17th loop it displays "bad luck from Italy"

i=1
while [ $i -le 20 ]
do
	echo "$i"

	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
