#!/usr/bin/env bash
# This script is used to configure nginx container to run as nginx user
chmod +rwx /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
